//#define SDK_USER_MQTT_URL "iot-as-mqtt.cn-shanghai.aliyuncs.com"
#define SDK_USER_ENABLE_AUTO_RECONNECT (1)
#define SDK_USER_CLEAN_SESSION (0)
#define SDK_USER_MQTT_HEART_BEAT_INTERVAL_MS (1000 * 120)
#define SDK_USER_MQTT_HEART_BEAT_MAX_LOST_NUM (3)
#define SDK_USER_OTA_CUR_VERSION  "" 
#define SDK_USER_OTA_AUTO_DOWNLOAD (0)
#define SDK_USER_OTA_AUTO_REPORT_VERSION (1)
#define SDK_DATA_MODEL_ENABLED (1)
#define ENCRYPT_TLS_ENABLED (1)
