cp buildroot_x2000_clever_common_defconfig /home/lzy/workspace/buildroot/buildroot/.config
cp x2000_halley5_module_clever_linux_sfc_nand_defconfig /home/lzy/workspace/kernel/kernel-x2000/.config
cp x2000_halley5_clever_nand_defconfig /home/lzy/workspace/build/configs/x2000_halley5_clever_nand_defconfig
